# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.

    session:
        enabled: true
    csrf_protection:
        enabled: true

    #esi: true
    #fragments: true

when@test:
    framework:
        rate_limiter:
            reset_password:
                policy: 'no_limit' # or increase limits
        test: true
        session:
            enabled: true
        csrf_protection:
            enabled: true
